@host = http://localhost:4006
@host2 = http://localhost:3001

###

GET {{host}}/odata/v4/admin


###

POST {{host2}}/odata/v4/admin/GalacticSpaceFarers
Content-Type: application/json

{
  "name": "Mike Zsacka",
  "stardustCollection": 10,
  "wormholeNavigationSkill": 23,
  "originPlanet": "Earth",
  "spacesuitColor": "Blue",
   "email": "mike.zsacka@gmail.com"
}



###
GET {{host2}}/odata/v4/admin/GalacticSpaceFarers